export const GENERATE_FACT = 'GENERATE_FACT';
export const GENERATE_FACT_IN_PROGRESS = 'GENERATE_FACT_IN_PROGRESS';
export const GENERATE_FACT_SUCCEEDED = 'GENERATE_FACT_SUCCEEDED';
export const GENERATE_FACT_FAILED = 'GENERATE_FACT_FAILED';
